/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Electricity/daily-data/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SingleDayData"];
                        "application/json": components["schemas"]["SingleDayData"];
                        "text/json": components["schemas"]["SingleDayData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Electricity/daily-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DailyDataRequest"];
                    "text/json": components["schemas"]["DailyDataRequest"];
                    "application/*+json": components["schemas"]["DailyDataRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PaginatedData"];
                        "application/json": components["schemas"]["PaginatedData"];
                        "text/json": components["schemas"]["PaginatedData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CheapestHour: {
            hour?: string | null;
            /** Format: double */
            price?: unknown;
        };
        DailyData: {
            /** Format: date */
            date?: string;
            productionAmount?: string | null;
            consumptionAmount?: string | null;
            /** Format: double */
            averageHourlyPrice?: unknown;
            cheapestHour?: components["schemas"]["CheapestHour"];
        };
        DailyDataRequest: {
            pagination?: components["schemas"]["Pagination"];
            sort?: components["schemas"]["SortOptions"];
            filters?: components["schemas"]["FilterOptions"];
        };
        FilterOptions: {
            date?: string;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            /** Format: double */
            minPrice?: unknown;
            /** Format: double */
            maxPrice?: unknown;
        };
        PaginatedData: {
            dailyRows?: components["schemas"]["DailyData"][];
            /** Format: int32 */
            allPages?: unknown;
        };
        Pagination: {
            /** Format: int32 */
            pageSize?: unknown;
            /** Format: int32 */
            pageNumber?: unknown;
        };
        SingleDayData: {
            /** Format: date */
            date?: string;
            productionTotal?: string | null;
            consumptionTotal?: string | null;
            /** Format: double */
            averageHourlyPrice?: unknown;
            allHourlyPrices?: unknown[];
        };
        SortOptions: {
            orderDir?: string;
            orderBy?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
